/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlaybookRouteImport } from './routes/_app/playbook'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppMyWeekRouteImport } from './routes/_app/my-week'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppFollowUpsRouteImport } from './routes/_app/follow-ups'
import { Route as AppFlyersRouteImport } from './routes/_app/flyers'
import { Route as AppCallRouteImport } from './routes/_app/call'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/_app/settings.workspace'
import { Route as AppSettingsTrainingDocsRouteImport } from './routes/_app/settings.training-docs'
import { Route as AppSettingsTemplatesRouteImport } from './routes/_app/settings.templates'
import { Route as AppSettingsObjectionsRouteImport } from './routes/_app/settings.objections'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings.members'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google.callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybookRoute = AppPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWeekRoute = AppMyWeekRouteImport.update({
  id: '/my-week',
  path: '/my-week',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppFlyersRoute = AppFlyersRouteImport.update({
  id: '/flyers',
  path: '/flyers',
  getParentRoute: () => AppRoute,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTrainingDocsRoute = AppSettingsTrainingDocsRouteImport.update({
  id: '/training-docs',
  path: '/training-docs',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTemplatesRoute = AppSettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsObjectionsRoute = AppSettingsObjectionsRouteImport.update({
  id: '/objections',
  path: '/objections',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AppCalendarRoute
  '/call': typeof AppCallRoute
  '/flyers': typeof AppFlyersRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/inbox': typeof AppInboxRoute
  '/my-week': typeof AppMyWeekRoute
  '/notes': typeof AppNotesRoute
  '/offers': typeof AppOffersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pipeline': typeof AppPipelineRoute
  '/playbook': typeof AppPlaybookRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/objections': typeof AppSettingsObjectionsRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/settings/training-docs': typeof AppSettingsTrainingDocsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/calendar': typeof AppCalendarRoute
  '/call': typeof AppCallRoute
  '/flyers': typeof AppFlyersRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/inbox': typeof AppInboxRoute
  '/my-week': typeof AppMyWeekRoute
  '/notes': typeof AppNotesRoute
  '/offers': typeof AppOffersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pipeline': typeof AppPipelineRoute
  '/playbook': typeof AppPlaybookRoute
  '/': typeof AppIndexRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/objections': typeof AppSettingsObjectionsRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/settings/training-docs': typeof AppSettingsTrainingDocsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/call': typeof AppCallRoute
  '/_app/flyers': typeof AppFlyersRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/my-week': typeof AppMyWeekRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/playbook': typeof AppPlaybookRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/objections': typeof AppSettingsObjectionsRoute
  '/_app/settings/templates': typeof AppSettingsTemplatesRoute
  '/_app/settings/training-docs': typeof AppSettingsTrainingDocsRoute
  '/_app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/call'
    | '/flyers'
    | '/follow-ups'
    | '/inbox'
    | '/my-week'
    | '/notes'
    | '/offers'
    | '/onboarding'
    | '/pipeline'
    | '/playbook'
    | '/settings'
    | '/settings/members'
    | '/settings/objections'
    | '/settings/templates'
    | '/settings/training-docs'
    | '/settings/workspace'
    | '/settings/'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/call'
    | '/flyers'
    | '/follow-ups'
    | '/inbox'
    | '/my-week'
    | '/notes'
    | '/offers'
    | '/onboarding'
    | '/pipeline'
    | '/playbook'
    | '/'
    | '/settings/members'
    | '/settings/objections'
    | '/settings/templates'
    | '/settings/training-docs'
    | '/settings/workspace'
    | '/settings'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/calendar'
    | '/_app/call'
    | '/_app/flyers'
    | '/_app/follow-ups'
    | '/_app/inbox'
    | '/_app/my-week'
    | '/_app/notes'
    | '/_app/offers'
    | '/_app/onboarding'
    | '/_app/pipeline'
    | '/_app/playbook'
    | '/_app/settings'
    | '/_app/'
    | '/_app/settings/members'
    | '/_app/settings/objections'
    | '/_app/settings/templates'
    | '/_app/settings/training-docs'
    | '/_app/settings/workspace'
    | '/_app/settings/'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbook': {
      id: '/_app/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AppPlaybookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-week': {
      id: '/_app/my-week'
      path: '/my-week'
      fullPath: '/my-week'
      preLoaderRoute: typeof AppMyWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flyers': {
      id: '/_app/flyers'
      path: '/flyers'
      fullPath: '/flyers'
      preLoaderRoute: typeof AppFlyersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call': {
      id: '/_app/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/workspace': {
      id: '/_app/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/training-docs': {
      id: '/_app/settings/training-docs'
      path: '/training-docs'
      fullPath: '/settings/training-docs'
      preLoaderRoute: typeof AppSettingsTrainingDocsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/templates': {
      id: '/_app/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AppSettingsTemplatesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/objections': {
      id: '/_app/settings/objections'
      path: '/objections'
      fullPath: '/settings/objections'
      preLoaderRoute: typeof AppSettingsObjectionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsObjectionsRoute: typeof AppSettingsObjectionsRoute
  AppSettingsTemplatesRoute: typeof AppSettingsTemplatesRoute
  AppSettingsTrainingDocsRoute: typeof AppSettingsTrainingDocsRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsObjectionsRoute: AppSettingsObjectionsRoute,
  AppSettingsTemplatesRoute: AppSettingsTemplatesRoute,
  AppSettingsTrainingDocsRoute: AppSettingsTrainingDocsRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCallRoute: typeof AppCallRoute
  AppFlyersRoute: typeof AppFlyersRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMyWeekRoute: typeof AppMyWeekRoute
  AppNotesRoute: typeof AppNotesRoute
  AppOffersRoute: typeof AppOffersRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPlaybookRoute: typeof AppPlaybookRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCallRoute: AppCallRoute,
  AppFlyersRoute: AppFlyersRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppInboxRoute: AppInboxRoute,
  AppMyWeekRoute: AppMyWeekRoute,
  AppNotesRoute: AppNotesRoute,
  AppOffersRoute: AppOffersRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPlaybookRoute: AppPlaybookRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
